homwork 5 from session 5
e0257/Angular-2 pull request #1
Opened 2017-05-07 13:08 UTC by e0257

2017-05-08 17:32 UTC, ghost requested changes
минорные правки

2017-05-08 17:32 UTC, captainkovalsky commented on HW-2017-05-02/src/app/film-card/film-card.service.ts
> +    return this.http.get(this.url + filmName).map(this.extractData);
При вводе несуществующего фильма API возвращает `{"Response":"False","Error":"Movie not found!"}` 
Это тоже нужно обрабатывать

2017-05-08 17:32 UTC, captainkovalsky commented on HW-2017-05-02/src/app/film-card/film-card.service.ts
> +import {Http, Response} from '@angular/http';
форматировка разная

2017-05-08 17:32 UTC, captainkovalsky commented on HW-2017-05-02/src/app/film-card/film-card.service.ts
> +  getFilms (filmName: string) {
Частичное использование TypeScript, нужно прописывать что возвращают методы

2017-05-08 17:32 UTC, captainkovalsky commented on HW-2017-05-02/src/app/film-card/film-card.component.ts
> +    this.filmCardService.getFilms(this.filmName).subscribe(data => {
непонятное название переменной data

2017-05-08 17:32 UTC, captainkovalsky commented on HW-2017-05-02/src/app/film-card/film-card.component.ts
> +    this.filmName = "Matrix"
TSLint style guide, в проекте есть tslint файл, если visual code то https://marketplace.visualstudio.com/items?itemName=eg2.tslint можно поставить

2017-05-08 17:32 UTC, captainkovalsky commented on HW-2017-05-02/src/app/film-card/film-card.component.html
> +  <md-input-container class="example-full-width">
код не отформатирован, не удобно читать

2017-05-08 21:34 UTC, e0257 commented on HW-2017-05-02/src/app/film-card/film-card.component.ts
> +    this.filmName = "Matrix"
добавил

2017-05-08 21:35 UTC, e0257 commented on HW-2017-05-02/src/app/film-card/film-card.service.ts
> +import {Http, Response} from '@angular/http';
использовал Alt+Shift+F на всеx файлах в App

2017-05-08 21:36 UTC, e0257 commented on HW-2017-05-02/src/app/film-card/film-card.service.ts
> +  getFilms (filmName: string) {
Добавил : any

2017-05-08 21:38 UTC, e0257 commented on HW-2017-05-02/src/app/film-card/film-card.service.ts
> +    return this.http.get(this.url + filmName).map(this.extractData);
Немного другой костыль наверное вставил (проверяю длину массива с фильмами в ngIf), но работает вроде ожидаемо

2017-05-08 21:40 UTC, e0257 commented on HW-2017-05-02/src/app/film-card/film-card.component.ts
> +    this.filmCardService.getFilms(this.filmName).subscribe(data => {
Изменил на films

2017-05-08 21:41 UTC, e0257 commented on HW-2017-05-02/src/app/film-card/film-card.component.html
> +  <md-input-container class="example-full-width">
использовал Alt+Shift+F на всеx файлах в App

2017-05-09 07:09 UTC, ghost approved these changes
approved

2017-05-09 07:09 UTC, captainkovalsky commented on HW-2017-05-02/src/app/film-card/film-card.service.ts
> +    return this.http.get(this.url + filmName).map(this.extractData);
Теперь намного лучше

2017-05-09 19:04 UTC, merged