Added homework_9
e0257/Angular-2 pull request #3
Opened 2017-05-21 18:28 UTC by e0257

Добавил задание по 9 сессии

2017-05-23 16:49 UTC, ghost requested changes
мелкие изменения

2017-05-23 16:49 UTC, captainkovalsky commented on HomeWork_9/src/app/film.service.ts
> +    return this.http.get(this.searchUrl + filmName).map(this.extractListFilms);
@e0257 Можно удалить одинаковые методы extractListFilms и extractFilm и использовать только анонимною функцию `(r: Response) => r.json() || {}`

2017-05-23 16:49 UTC, captainkovalsky commented on HomeWork_9/src/app/film-card/film-card.component.ts
> +  filmItem: {} = {};
@e0257 описать interface/class для  filmItem

2017-05-23 16:49 UTC, captainkovalsky commented on HomeWork_9/src/app/film-card/film-card.component.ts
> +  constructor(private filmCardService: FilmService) { }
@e0257 нейминг: использовать просто filmService имя

2017-05-23 16:49 UTC, captainkovalsky commented on HomeWork_9/src/app/film.service.ts
> +    return this.http.get(this.searchUrl + filmName).map(this.extractListFilms);
использовать класс для явного указания что возвращается `<Film[]> r.json()`

2017-05-23 18:09 UTC, ghost requested changes
мелкие изменения

2017-05-24 20:38 UTC, e0257 commented
Применил все что ты сказал. По мне так внедрение интерфейса для фильмов усложнило код. 
1) Для интерфейса нужно прописать какие-то поля, я выбрал те что использовал с приходящего объекта
2) Также объект по-умолчанию { } уже не подходит и все что мне пришло в голову подставлять по умолчанию {
    Released: '',
    Plot: '',
    Genre: '',
    imdbRating: '',
    Director: '',
    Runtime: ''
  }

2017-05-25 20:23 UTC, ghost approved these changes
хорошо

2017-05-25 20:23 UTC, captainkovalsky commented on HomeWork_9/src/app/int-film.ts
> +export interface Film {
@e0257 За интерфейс плюс

2017-05-26 04:48 UTC, merged