Homework13
e0257/Angular-2 pull request #6
Opened 2017-07-09 19:57 UTC by e0257

Последняя версия сайта с фильмами....делал все с нуля. Вроде пока все работает .

Не могу никак сделать чернобелую картинку заднего фона. Никак не получается. Просьба помочь.

Также жду замечаний по коду

2017-07-17 08:57 UTC, fullstackdb commented
О фильтре к картинке:
туториал на w3c как сделать чорнобелый фильтр [ссылка](https://www.w3schools.com/cssref/css3_pr_filter.asp)
статья на хабре, в конце статьи есть пример применения фільтров к беграунд картинкам [ссылка](https://habrahabr.ru/post/264037/)
статья на css tricks [ссылка](https://css-tricks.com/almanac/properties/f/filter/)
кодепен с фильтром на беграунд имедже [ссылка](https://codepen.io/bookcasey/pen/rAJcp)

2017-07-17 09:25 UTC, fullstackdb requested changes
незначительные изминения запрошены

2017-07-17 09:25 UTC, fullstackdb commented on FilmsSiteMain/src/app/app.component.html
> +      &copy; YBFilms
удалить символ &copy;, реализовать даное поведение при помощи css

2017-07-17 09:25 UTC, fullstackdb commented on FilmsSiteMain/src/app/app.component.ts
> +}
форматировка

удалить неиспользованый хук и filmService

2017-07-17 09:25 UTC, fullstackdb commented on FilmsSiteMain/src/app/film-card/film-card.component.html
> +<div class="film-card_v" *ngIf="filmDetail&&filmService.viewOfFilms === 'V'">
вынесите проверки в метод компонента

2017-07-17 09:25 UTC, fullstackdb commented on FilmsSiteMain/src/app/film-card/film-card.component.html
> +	<a id = "{{filmDetail.id}}" routerLink="/film/{{filmDetail.id}}" title="{{filmDetail.title}}" >
атрибуты, значение которих байндиться(добавляеться динамически), необхоимо заключать в скобки `[id] [title] etc`

касаеться всех подобных мест

2017-07-17 09:25 UTC, fullstackdb commented on FilmsSiteMain/src/app/film-card/film-card.component.ts
> +  }
исправить форматировку

не до конца используеться тайпскрипт
- добавьте использование типов 
- добавьте использование ключевых слов к методам

используйте хуки для инициализации работы с сервисом

2017-07-17 09:25 UTC, fullstackdb commented on FilmsSiteMain/src/app/film-info/film-info.component.ts
> +    }
форматировка

2017-07-17 09:25 UTC, fullstackdb commented on FilmsSiteMain/src/app/film-list/film-list.component.ts
> +    }
форматировка

2017-07-17 09:25 UTC, fullstackdb commented on FilmsSiteMain/src/app/films-list-favorites/films-list-favorites.component.ts
> +    document.body.style.background = "#dbd5f4";
пожелание:
реализовать даное поведение через Renderer2 [документация](https://angular.io/api/core/Renderer2) [статья на медиуме](https://netbasal.com/angular-2-explore-the-renderer-service-e43ef673b26c)

2017-07-17 09:25 UTC, fullstackdb commented on FilmsSiteMain/src/app/films-list-favorites/films-list-favorites.component.ts
> +          favorites.forEach(filmItem => {
реализовать даное поведение через операторы observable
[статья](https://coryrylan.com/blog/angular-multiple-http-requests-with-rxjs)

2017-07-17 09:25 UTC, fullstackdb commented on FilmsSiteMain/src/app/films-list-favorites/films-list-favorites.component.ts
> +  }
форматировка

2017-07-17 09:25 UTC, fullstackdb commented on FilmsSiteMain/src/app/search/search.component.ts
> +      if(!this.searchValue) return;
переписать в более очевидную проверку
```
if(this.searchValue) {
// code
}
```

2017-07-17 09:25 UTC, fullstackdb commented on FilmsSiteMain/src/app/search/search.component.ts
> +  }
форматировка компонента

2017-07-19 19:59 UTC, e0257 commented on FilmsSiteMain/src/app/app.component.ts
> +}
убрал

2017-07-19 20:15 UTC, e0257 commented on FilmsSiteMain/src/app/film-card/film-card.component.html
> +<div class="film-card_v" *ngIf="filmDetail&&filmService.viewOfFilms === 'V'">
Сделал так filmDetail&&viewOfFilms === 'V'
viewOfFilms - сделал гетером в компоненте
Иначе не могу, так как viewOfFilms  зависит в каком виде будут отображаться карточки фильмов... вводить две переменные которые будут отвечать за каждый вид

2017-07-19 20:43 UTC, e0257 commented on FilmsSiteMain/src/app/film-card/film-card.component.html
> +	<a id = "{{filmDetail.id}}" routerLink="/film/{{filmDetail.id}}" title="{{filmDetail.title}}" >
Вроде все изменил, что увидел

2017-07-19 21:10 UTC, e0257 commented on FilmsSiteMain/src/app/films-list-favorites/films-list-favorites.component.ts
> +  }
сделал

2017-07-19 21:10 UTC, e0257 commented on FilmsSiteMain/src/app/search/search.component.ts
> +  }
сделал

2017-07-19 21:11 UTC, e0257 commented on FilmsSiteMain/src/app/film-list/film-list.component.ts
> +    }
сделал

2017-07-19 21:23 UTC, e0257 commented on FilmsSiteMain/src/app/film-info/film-info.component.ts
> +    }
тут особо не вижу что именно

2017-07-19 21:32 UTC, e0257 commented on FilmsSiteMain/src/app/search/search.component.ts
> +      if(!this.searchValue) return;
Сделал

2017-07-19 21:33 UTC, e0257 commented on FilmsSiteMain/src/app/app.component.html
> +      &copy; YBFilms
не понял зачем так,  но сделал

2017-07-21 20:52 UTC, e0257 commented on FilmsSiteMain/src/app/films-list-favorites/films-list-favorites.component.ts
> +          favorites.forEach(filmItem => {
Не получилось, проблему писал в чате

2017-07-26 18:47 UTC, e0257 commented on FilmsSiteMain/src/app/films-list-favorites/films-list-favorites.component.ts
> +          favorites.forEach(filmItem => {
С вашей помощью, но сделал

2017-08-04 20:39 UTC, e0257 commented on FilmsSiteMain/src/app/films-list-favorites/films-list-favorites.component.ts
> +    document.body.style.background = "#dbd5f4";
сделал

2017-08-04 20:49 UTC, e0257 commented on FilmsSiteMain/src/app/film-card/film-card.component.ts
> +  }
Что-то исправил, что-то может нет

2017-09-17 10:01 UTC, e0257 commented
Merge to Master

2017-09-17 10:02 UTC, merged