Homework15
e0257/Angular-2 pull request #7
Opened 2017-07-10 21:05 UTC by e0257

2017-07-17 09:34 UTC, fullstackdb requested changes
Незначительные изминения запрошены

2017-07-17 09:34 UTC, fullstackdb commented on HomeWork_15(forms)/src/app/app.component.css
> +
форматировка

2017-07-17 09:34 UTC, fullstackdb commented on HomeWork_15(forms)/src/app/app.component.ts
> +  title = 'app works!';
удалить неиспользованую переменную

2017-07-17 09:34 UTC, fullstackdb commented on HomeWork_15(forms)/src/app/charge-phone/charge-phone.component.html
> +        CVS is not valid
перенести меседжы в константы

продвинутый вариант:
использовать i18n [ссылка](https://angular.io/guide/i18n)

2017-07-17 09:34 UTC, fullstackdb commented on HomeWork_15(forms)/src/app/charge-phone/charge-phone.component.ts
> +  selectYear;// = this.years[0];
перенести значение переменных в сервис и тянуть их асинхронно

2017-07-17 09:34 UTC, fullstackdb commented on HomeWork_15(forms)/src/app/login/login.component.ts
> +  constructor(private router: Router) { }
удалить неиспользованую зависимость

2017-07-17 09:34 UTC, fullstackdb commented on HomeWork_15(forms)/src/app/login/login.component.ts
> +  ngOnInit() {
удалить неиспользованый хук

2017-07-17 09:34 UTC, fullstackdb commented on HomeWork_15(forms)/src/app/success-charge-phone/success-charge-phone.component.html
> +<p>
использовать классы

2017-07-17 09:34 UTC, fullstackdb commented on HomeWork_15(forms)/src/app/success-charge-phone/success-charge-phone.component.css
> +p{
использовать классы вместо селекторов

2017-07-17 09:34 UTC, fullstackdb commented on HomeWork_15(forms)/src/app/success-charge-phone/success-charge-phone.component.ts
> +  }
удалить неиспользованый хук

2017-07-25 19:59 UTC, e0257 commented
All changes will be in homework16

2017-07-25 20:00 UTC, merged