Add homework16 and changes from homework15
e0257/Angular-2 pull request #8
Opened 2017-07-25 20:01 UTC by e0257

2017-07-31 20:14 UTC, fullstackdb requested changes
незначительные изминения запрошены

2017-07-31 20:14 UTC, fullstackdb commented on homework_16/src/app/app.component.html
> +  <h1>Супер пополнялка</h1>
рекомендация:
- использовать i18n  для работы со строками [документация](https://angular.io/guide/i18n)

2017-07-31 20:14 UTC, fullstackdb commented on homework_16/src/app/app.module.ts
> +
удалите лишние пробелы

2017-07-31 20:14 UTC, fullstackdb commented on homework_16/src/app/auth-service.service.ts
> +  checkAuth(login, password){
удалить локальные переменные с данными

реализовать даное поведение через мок вызова API

использовать типы и observable

```
return Observable.of({ status: true })
```

2017-07-31 20:14 UTC, fullstackdb commented on homework_16/src/app/charge-phone/charge-phone.component.ts
> +  years = ["2017","2018", "2019","2020"]
перенести значение в сервисы и получать их асинхронно.

совет:
Для полноценной емуляции работы с бекендом посмотрите в сторону [json-server](https://github.com/typicode/json-server).

2017-07-31 20:14 UTC, fullstackdb commented on homework_16/src/app/login/login.component.ts
> +     this.authtorisation = this.authService.checkAuth(this.email, this.password);
удалите лишние пробелы више

работайте через Observble , помните everything is stream

```
this.authService.isLoggined(this.email, this.password).subscribe( (status: IAuthStatus) => { if (status) { this.router.navigate(['/charge']);  } } )

```

2017-07-31 20:14 UTC, fullstackdb commented on homework_16/src/app/success-charge-phone/success-charge-phone.component.ts
> +  ngOnInit() {
удалить неиспользуемые конструкции

2017-08-06 17:50 UTC, e0257 commented on homework_16/src/app/app.component.html
> +  <h1>Супер пополнялка</h1>
не совсем понял что оно делает в итоге, как увидеть что оно действует....если что сам еще поколдую

2017-08-06 17:50 UTC, e0257 commented on homework_16/src/app/app.module.ts
> +
удалил

2017-08-06 17:56 UTC, e0257 commented on homework_16/src/app/auth-service.service.ts
> +  checkAuth(login, password){
сделал импорт в сервис import { Observable } from 'rxjs/Observable';
Observable.of - ругается что нет такого метода, Observable.from тоже....

2017-08-06 17:58 UTC, e0257 commented on homework_16/src/app/login/login.component.ts
> +     this.authtorisation = this.authService.checkAuth(this.email, this.password);
Причина почему это не работает я назвал выше:

сделал импорт в сервис import { Observable } from 'rxjs/Observable';
Observable.of - ругается что нет такого метода, Observable.from тоже....

2017-08-06 17:58 UTC, e0257 commented on homework_16/src/app/success-charge-phone/success-charge-phone.component.ts
> +  ngOnInit() {
удалил

2017-08-07 20:28 UTC, fullstackdb approved these changes

2017-09-17 10:04 UTC, merged